### ISSUE TITLE
FR13: The WeCare application could provide a login.

### ISSUE THREAD

**Issue by jfalzaed** [Salome-Serna-R/WeCare#28]

**Comment by jfalzaed** [comment]
Validation criteria:
- Check that the system handles user sessions efficiently, keeping the session active according to the user's needs and logging out securely.
- The system should validate that the information provided does exist in the user database.

**Comment by Salome-Serna-R** [comment]
- After completing a session with a psychologist, the option to rate the psychologist should be available to the student on the application.
- The application should allow the patient to rate the psychologist using the defined scale.
- Grades given by patients must be correctly stored in the database and be visible to other students and psychologists.
